config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :products
  resources :chats, only: %i[ index new show ]
  resources :messages, only: %i[ create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :product
  belongs_to :owner, class_name: 'User'
  belongs_to :buyer, class_name: 'User'
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :chats
  belongs_to :user
  enum available: { disponivel: true , indisponivel: false }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :owner_chats, class_name: 'Chat', foreign_key: 'owner_id'
  has_many :buyer_chats, class_name: 'Chat', foreign_key: 'buyer_id'
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only: %i[ index new ]
  before_action :find_chat, only: %i[ index]
  def index
    show_or_new_chat
  end

  def new
    @chat = @product.chats.new(owner: @product.user, buyer: current_user)
    return redirect_to products_path unless validate_owner_buyer
    redirect_to @chat if @chat.save
  end

  def show
    set_chat
    @message = Message.new
  end

  private

  def find_product
    @product = Product.find(params[:product_id]) || nil
  end

  def find_chat
    @chat = Chat.find_by(product: @product, buyer: current_user) || nil
  end

  def show_or_new_chat
    return redirect_to products_path if @product.nil?
    return redirect_to new_chat_path(product_id: @product) if @chat.nil?
    redirect_to @chat
  end

  def validate_owner_buyer
    !@chat.owner.eql?@chat.buyer
  end

  def set_chat
    if current_user.buyer_chats.include? Chat.find(params[:id])
      @chat = current_user.buyer_chats.find(params[:id])
    else
      @chat = current_user.owner_chats.find(params[:id])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  def create
    return redirect products_path unless belongs_this_chat
    @message = @chat.messages.new(body: message_params[:body], user: current_user)
    return redirect_to @chat if @message.save
  end

  private

  def message_params
    params.require(:message).permit(:body, :chat)
  end

  def find_chat
    @chat = Chat.find(message_params[:chat])
  end
  def belongs_this_chat
    find_chat
    return true if current_user.owner_chats.include?@chat
    return true if current_user.buyer_chats.include?@chat
    false
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_owner_product, only: %i[ edit update destroy ]

  def index
    @owner = params[:owner] || 'all'
    @products  = current_user.products if @owner == 'myself'
    @products  = Product.all if @owner == 'all'
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.new(product_params)

    return redirect_to @product if @product.save

    redner :new
  end

  def show
    @product = Product.find(params[:id])
    if current_user.products.include?(Product.find(params[:id]))
      @chats = @product.chats
    end
  end

  def edit
  end

  def update
    return redirect_to products_path if @product.update(product_params)

    render :edit
  end

  def destroy
    @product.destroy

    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :available)
  end

  def find_owner_product
    @product = current_user.products.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/show.html.erb
<h2>Chat</h2>

<p>Produto: <%= @chat.product.user.email %></p>
<p>Dono: <%= @chat.product.name %></p>
<p>Valor: <%= number_to_currency @chat.product.price, precision: 1, unit: 'R$' %></p>
<p>Status: <%= @chat.product.available %></p>

<%= form_with model: @message , local: true do |form| %>
  <p><%= form.label :body, 'Mensagem' %></p>
  <p><%= form.text_field :body %></p>

  <%= form.hidden_field :chat, value: @chat.id %>
  
  <p><%= form.submit %></p>
<% end %>

<hr>

<% @chat.messages.each do |message| %>
  <p>
    <%= message.user.email %> - 
    <%= message.body %>
  </p>
<% end %>

app/views/home/index.html.erb
<h2>Index</h2>
<%= link_to 'Produtos', products_path(owner: 'all') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MercadoTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <h1>Market</h1>
    <p>
      <% if user_signed_in? %>
        <%= current_user.email %> | 
      <% end %>
      <%= link_to 'Produtos', products_path %> | 

      <% unless user_signed_in? %>
        <%= link_to 'login', new_user_session_path%>
      <% else %>
        <%= link_to 'logout', destroy_user_session_path, method: :delete %>
      <% end %>
       
      

    </p>
    <hr style="background-color: green; height: 5px">
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |f| %>
  <p>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :price, 'R$' %>
    <%= f.number_field :price %>
  </p>
  
  <p>
    <%= f.label :available, 'Disponivel' %>
    <%= f.select :available, [ :disponivel, :indisponivel ]%>
  </p>

  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>
<%= render partial: 'form' %>

app/views/products/index.html.erb
<h2>Products list</h2>

<p>
  <%= link_to 'Adicionar', new_product_path %> |
  <% if @owner == 'all' %>
    <%= link_to 'Meus Produtos', products_path(owner: 'myself') %>
  <% else %>
    <%= link_to 'Todos Os Produtos', products_path(owner: 'all') %>
  <% end %>
</p>

<hr style="background-color: blue; height: 5px">

<% @products.each do |product| %>

  <p>Nome: <%= link_to product.name, product %></p>
  <p>valor: <%= number_to_currency product.price, precision: 1, unit: 'R$' %></p>
  <p>status: <%= product.available %></p>
  <p>owner: <%= product.user.email %></p>

  <% if current_user.products.include? product %>
    <p>
      <%= link_to 'Editar', edit_product_path(product)%> |
      <%= link_to 'Apagar', product, method: :delete %> 
    </p>
  <% else %>
    <p>
      <%= link_to 'Negociar', chats_path(product_id: product.id) %>
    </p>
  <% end %>
  <hr>
<% end %>

app/views/products/new.html.erb
<h2>New Product</h2>
<%= render partial: 'form' %>

app/views/products/show.html.erb
<h2>Product details</h2>

<p>Nome: <%= @product.name %></p>
<p>valor: <%= number_to_currency @product.price, precision: 1, unit: 'R$' %></p>
<p>status: <%= @product.available %></p>

<% if @chats %>
  <% @chats.each do |chat| %>
  <p><%= link_to chat.buyer.email , chat %></p>
  <% end %>
<% end %>

<% unless current_user.products.include? @product %>
  <%= link_to 'Negociar', chats_path(product_id: @product.id) %>
<% end %>